basePath: /
definitions:
  dto.CreateTaskRequest:
    properties:
      assignee:
        type: string
      description:
        type: string
      status:
        enum:
        - todo
        - doing
        - done
        type: string
      title:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - status
    - title
    type: object
  dto.UpdateTaskRequest:
    properties:
      assignee:
        type: string
      description:
        type: string
      status:
        enum:
        - todo
        - doing
        - done
        type: string
      title:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - status
    - title
    type: object
  entity.Task:
    properties:
      assignee:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Interview Task Manager Service
  title: Task Manager API
  version: "1.0"
paths:
  /tasks:
    get:
      parameters:
      - description: Filter by status
        in: query
        name: status
        type: string
      - description: Filter by assignee
        in: query
        name: assignee
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task payload
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete task
      tags:
      - tasks
    get:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Task'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Task payload
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update task
      tags:
      - tasks
swagger: "2.0"
